FROM busybox:latest
VOLUME ["/data"]
CMD while :; do echo 'Far away there in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty, believe in them, and try to follow where they lead.' >> /data/logB; sleep 1; done
